os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_USERNAME="jgsogo"
    - CONAN_CHANNEL="ci"
    - CONAN_TOTAL_PAGES=8
    - CONAN_PIP_PACKAGE="conan --upgrade"  # When using docker this is how we can install pacakges there (needed for sqlite3cc/dev@jgsogo/ci

  matrix:
    - CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=1
    - CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=2
    - CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=3
    - CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=4
    - CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=5
    - CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=6
    - CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=7
    - CONAN_USE_DOCKER=1 CONAN_CURRENT_PAGE=8
matrix:
   include:
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.3
         language: generic
         env:
       - os: osx
         osx_image: xcode8.1 # apple-clang 8.1
         language: generic
         env:

install:
  - chmod ugo+x ./.travis/install.sh
  - chmod ugo+x ./.travis/run.sh
  - ./.travis/install.sh

script:
  - ./.travis/run.sh
