build: false
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.11"
    PYTHON_ARCH: "32"

    CONAN_UPLOAD: 1
    CONAN_USERNAME: "jgsogo"
    CONAN_CHANNEL: "ci"
    CONAN_TOTAL_PAGES: 4

    matrix:
        - CONAN_CURRENT_PAGE: 1
        - CONAN_CURRENT_PAGE: 2
        - CONAN_CURRENT_PAGE: 3
        - CONAN_CURRENT_PAGE: 4
install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools # It installs conan too
  - conan user # It creates the conan data directory
  # Need bzr to compile sqlite3cc/dev@jgsogo/ci
  - choco install -y --force bzr
  - set PATH=C:\Program Files (x86)\Bazaar;%PATH%
  - bzr --version

test_script:
  - C:\Python27\python build.py
