build: false
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.11"
    PYTHON_ARCH: "32"

    CONAN_UPLOAD: 1
    CONAN_REFERENCE: "queryset-cpp/0.4"
    CONAN_USERNAME: "jgsogo"
    CONAN_CHANNEL: "ci"
    CONAN_TOTAL_PAGES: 4

    matrix:
        - CONAN_CURRENT_PAGE: 1
        - CONAN_CURRENT_PAGE: 2
        - CONAN_CURRENT_PAGE: 3
        - CONAN_CURRENT_PAGE: 4
install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools # It installs conan too
  - conan user # It creates the conan data directory

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: conan install .. --scope queryset-cpp:BUILD_TEST=ON
  - cmd: cmake .. -G "Visual Studio 14 2015 Win64"
  - cmd: cmake --build . --config Release
  
test_script:
  - cmd: cd bin
  - cmd: test_queryset_utils.exe
  - cmd: test_queryset.exe
  - cmd: test_models.exe
  - cmd: cd ../..
  - C:\Python27\python build.py
